export const cartActions = {
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_REMOVE_ALL_ITEMS: 'CART_REMOVE_ALL_ITEMS',
  CART_ADD_SHIPPING_ADDRESS: 'CART_ADD_SHIPPING_ADDRESS',
  CART_ADD_PAYMENT_METHOD: 'CART_ADD_PAYMENT_METHOD',
}
