export const orderActions = {
  ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',

  ORDERED_PROD_CREATE_REQUEST: 'ORDERED_PROD_CREATE_REQUEST',
  ORDERED_PROD_CREATE_SUCCESS: 'ORDERED_PROD_CREATE_SUCCESS',
  ORDERED_PROD_CREATE_FAIL: 'ORDERED_PROD_CREATE_FAIL',
}
