export const orderActions = {
  ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',

  ORDERED_PRODS_CREATE_REQUEST: 'ORDERED_PRODS_CREATE_REQUEST',
  ORDERED_PRODS_CREATE_SUCCESS: 'ORDERED_PRODS_CREATE_SUCCESS',
  ORDERED_PRODS_CREATE_FAIL: 'ORDERED_PRODS_CREATE_FAIL',

  ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
  ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
  ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',

  ORDERED_PRODS_DETAILS_REQUEST: 'ORDERED_PRODS_DETAILS_REQUEST',
  ORDERED_PRODS_DETAILS_SUCCESS: 'ORDERED_PRODS_DETAILS_SUCCESS',
  ORDERED_PRODS_DETAILS_FAIL: 'ORDERED_PRODS_DETAILS_FAIL',
}
