export const orderActions = {
  ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',
  ORDER_CREATE_RESET: 'ORDER_CREATE_RESET',

  ORDERED_PRODS_CREATE_REQUEST: 'ORDERED_PRODS_CREATE_REQUEST',
  ORDERED_PRODS_CREATE_SUCCESS: 'ORDERED_PRODS_CREATE_SUCCESS',
  ORDERED_PRODS_CREATE_FAIL: 'ORDERED_PRODS_CREATE_FAIL',

  ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
  ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
  ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',
  ORDER_DETAILS_RESET: 'ORDER_DETAILS_RESET',

  ORDERED_PRODS_LIST_REQUEST: 'ORDERED_PRODS_LIST_REQUEST',
  ORDERED_PRODS_LIST_SUCCESS: 'ORDERED_PRODS_LIST_SUCCESS',
  ORDERED_PRODS_LIST_FAIL: 'ORDERED_PRODS_LIST_FAIL',

  ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
  ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
  ORDER_PAY_FAIL: 'ORDER_PAY_FAIL',
  ORDER_PAY_RESET: 'ORDER_PAY_RESET',

  ORDER_LIST_USER_REQUEST: 'ORDER_LIST_USER_REQUEST',
  ORDER_LIST_USER_SUCCESS: 'ORDER_LIST_USER_SUCCESS',
  ORDER_LIST_USER_FAIL: 'ORDER_LIST_USER_FAIL',
  ORDER_LIST_USER_RESET: 'ORDER_LIST_USER_RESET',

  ORDER_LIST_ADMIN_REQUEST: 'ORDER_LIST_ADMIN_REQUEST',
  ORDER_LIST_ADMIN_SUCCESS: 'ORDER_LIST_ADMIN_SUCCESS',
  ORDER_LIST_ADMIN_FAIL: 'ORDER_LIST_ADMIN_FAIL',
  ORDER_LIST_ADMIN_RESET: 'ORDER_LIST_ADMIN_RESET',

  ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
  ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',
  ORDER_LIST_FAIL: 'ORDER_LIST_FAIL',
}
