export const productActions = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',
  PRODUCT_LIST_RESET: 'PRODUCT_LIST_RESET',

  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAIL: 'PRODUCT_DETAILS_FAIL',
  PRODUCT_DETAILS_RESET: 'PRODUCT_DETAILS_RESET',

  PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
  PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
  PRODUCT_DELETE_FAIL: 'PRODUCT_DELETE_FAIL',

  PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
  PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  PRODUCT_CREATE_FAIL: 'PRODUCT_CREATE_FAIL',
  PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',

  PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAIL: 'PRODUCT_UPDATE_FAIL',
  PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',

  PRODUCT_UPDATE_COUNT_IN_STOCK_REQUEST:
    'PRODUCT_UPDATE_COUNT_IN_STOCK_REQUEST',
  PRODUCT_UPDATE_COUNT_IN_STOCK_SUCCESS:
    'PRODUCT_UPDATE_COUNT_IN_STOCK_SUCCESS',
  PRODUCT_UPDATE_COUNT_IN_STOCK_FAIL: 'PRODUCT_UPDATE_COUNT_IN_STOCK_FAIL',

  PRODUCT_REVIEW_LIST_REQUEST: 'PRODUCT_REVIEW_LIST_REQUEST',
  PRODUCT_REVIEW_LIST_SUCCESS: 'PRODUCT_REVIEW_LIST_SUCCESS',
  PRODUCT_REVIEW_LIST_FAIL: 'PRODUCT_REVIEW_LIST_FAIL',

  PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
  PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
  PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
  PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

  ADM_PRODUCT_LIST_REQUEST: 'ADM_PRODUCT_LIST_REQUEST',
  ADM_PRODUCT_LIST_SUCCESS: 'ADM_PRODUCT_LIST_SUCCESS',
  ADM_PRODUCT_LIST_FAIL: 'ADM_PRODUCT_LIST_FAIL',
}
