export const userActions = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGOUT: 'USER_LOGOUT',

  USER_LOGOUT_REQUEST: 'USER_LOGOUT',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT',
  USER_LOGOUT_FAIL: 'USER_LOGOUT',

  USER_SIGNUP_REQUEST: 'USER_SIGNUP_REQUEST',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAIL: 'USER_SIGNUP_FAIL',

  USER_DETAILS_REQUEST: 'USER_DETAILS_REQUEST',
  USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
  USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',
  USER_DETAILS_RESET: 'USER_DETAILS_RESET',

  USER_UPDATE_PROFILE_REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  USER_UPDATE_PROFILE_FAIL: 'USER_UPDATE_PROFILE_FAIL',
  USER_UPDATE_PROFILE_RESET: 'USER_UPDATE_PROFILE_RESET',

  USER_UPDATE_PASSWORD_REQUEST: 'USER_UPDATE_PASSWORD_REQUEST',
  USER_UPDATE_PASSWORD_SUCCESS: 'USER_UPDATE_PASSWORD_SUCCESS',
  USER_UPDATE_PASSWORD_FAIL: 'USER_UPDATE_PASSWORD_FAIL',
  USER_UPDATE_PASSWORD_RESET: 'USER_UPDATE_PASSWORD_RESET',

  USER_LIST_REQUEST: 'USER_LIST_REQUEST',
  USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
  USER_LIST_FAIL: 'USER_LIST_FAIL',
  USER_LIST_RESET: 'USER_LIST_RESET',

  USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
  USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  USER_DELETE_FAIL: 'USER_DELETE_FAIL',

  ADMIN_USER_UPDATE_PROFILE_REQUEST: 'ADMIN_USER_UPDATE_PROFILE_REQUEST',
  ADMIN_USER_UPDATE_PROFILE_SUCCESS: 'ADMIN_USER_UPDATE_PROFILE_SUCCESS',
  ADMIN_USER_UPDATE_PROFILE_FAIL: 'ADMIN_USER_UPDATE_PROFILE_FAIL',
}
